jenkinsci/soapui-pro-functional-testing-plugin

src/main/java/com/smartbear/ready/jenkins/JenkinsSoapUIProTestRunner.java
https://smartbear.atlassian.net/browse/RIA-7991
=> RIA-7991 fail build if tests failed

src/main/java/com/smartbear/ready/jenkins/JUnitReportPublisher.java, src/main/java/com/smartbear/ready/jenkins/JenkinsSoapUIProTestRunner.java
https://smartbear.atlassian.net/browse/RIA-8132
=> RIA-8132 Fixed JUnit plugin integration to work on slave

src/main/java/com/smartbear/ready/jenkins/JUnitReportPublisher.java, src/main/java/com/smartbear/ready/jenkins/JenkinsSoapUIProTestRunner.java, src/main/java/com/smartbear/ready/jenkins/ProcessRunner.java
https://smartbear.atlassian.net/browse/RIA-8170
=> RIA-8170 wrong report path on Linux slave

src/main/java/com/smartbear/ready/jenkins/JenkinsSoapUIProTestRunner.java
https://smartbear.atlassian.net/browse/RIA-8176
=> RIA-8176 Fixed misprints in the error message

src/main/java/com/smartbear/ready/jenkins/ProcessRunner.java
https://smartbear.atlassian.net/browse/RIA-8417
=> RIA-8417 change q parameter behavior

src/main/java/com/smartbear/ready/jenkins/JenkinsSoapUIProTestRunner.java
https://smartbear.atlassian.net/browse/RIA-8454
=> RIA-8454 Fixed text fields for pipeline

src/main/java/com/smartbear/ready/jenkins/JenkinsSoapUIProTestRunner.java, src/main/java/com/smartbear/ready/jenkins/ParameterContainer.java, src/main/java/com/smartbear/ready/jenkins/ProcessRunner.java, src/main/resources/com/smartbear/ready/jenkins/JenkinsSoapUIProTestRunner/config.jelly
https://smartbear.atlassian.net/browse/RIA-11573
=> RIA-11573 Add execution using tags

src/main/java/com/smartbear/ready/jenkins/JenkinsSoapUIProTestRunner.java, src/main/java/com/smartbear/ready/jenkins/ParameterContainer.java, src/main/java/com/smartbear/ready/jenkins/ProcessRunner.java, src/main/resources/com/smartbear/ready/jenkins/JenkinsSoapUIProTestRunner/config.jelly
https://smartbear.atlassian.net/browse/RIA-11573
=> RIA-11573 Implement separate tags for Test Case and Test Suite

README.md, pom.xml
https://smartbear.atlassian.net/browse/RIA-12292
=> RIA-12292 Update and move to GitHub the documentation

src/main/java/com/smartbear/ready/jenkins/ProcessRunner.java
https://smartbear.atlassian.net/browse/RIA-12811
=> RIA-12811 Skip length for directory

README.md
Update README.md for plugin release 1.3
=> Update README.md for release 1.3

pom.xml, src/main/java/com/smartbear/ready/jenkins/JenkinsSoapUIProTestRunner.java
https://smartbear.atlassian.net/browse/RIA-12990
=> RIA-12990 Mask password for project

src/main/java/com/smartbear/ready/jenkins/JenkinsSoapUIProTestRunner.java
https://smartbear.atlassian.net/browse/RIA-14439
=> RIA-14439 Hide password

README.md, pom.xml, src/main/java/com/smartbear/ready/jenkins/DynamicReportAction.java, src/main/java/com/smartbear/ready/jenkins/JenkinsSoapUIProTestRunner.java, src/main/java/com/smartbear/ready/jenkins/PrintableReportPublisher.java, src/main/java/com/smartbear/ready/jenkins/ProcessRunner.java, src/main/java/com/smartbear/ready/jenkins/SoapUIProTestResultsAction.java, src/main/resources/com/smartbear/ready/jenkins/JenkinsSoapUIProTestRunner/config.jelly, src/main/resources/com/smartbear/ready/jenkins/SoapUIProTestResultsAction/index.jelly, src/main/resources/index.jelly
https://smartbear.atlassian.net/browse/RIA-14445
=> RIA-14445 Renamed SoapUI Pro to ReadyAPI Test

README.md
=> update release notes for 1.7

README.md, pom.xml, src/main/java/com/smartbear/ready/jenkins/AuthMethod.java, src/main/java/com/smartbear/ready/jenkins/JenkinsSoapUIProTestRunner.java, src/main/java/com/smartbear/ready/jenkins/ParameterContainer.java, src/main/java/com/smartbear/ready/jenkins/ProcessRunner.java, src/main/resources/com/smartbear/ready/jenkins/JenkinsSoapUIProTestRunner/config.jelly, src/test/java/com/smartbear/ready/jenkins/JenkinsSoapUIProTestRunnerTest.java, src/test/java/com/smartbear/ready/jenkins/ProcessRunnerTest.java
https://smartbear.atlassian.net/browse/RIA-21001
```[tasklist]
```
=> Ria 21001 extend support for slm

pom.xml
Upgrade versions
```[tasklist]
```
=> Ria 21085 user password should work with saas

README.md, pom.xml, src/main/java/com/smartbear/ready/jenkins/JenkinsSoapUIProTestRunner.java, src/test/java/com/smartbear/ready/jenkins/JenkinsSoapUIProTestRunnerTest.java
=> RIA-21085: rollback changes

README.md, src/main/java/com/smartbear/ready/jenkins/JenkinsSoapUIProTestRunner.java, src/main/resources/com/smartbear/ready/jenkins/JenkinsSoapUIProTestRunner/config.jelly, src/test/java/com/smartbear/ready/jenkins/JenkinsSoapUIProTestRunnerTest.java
=> RIA-21617: remove user and password support for SmartBear hosted licenses

README.md
=> RIA-22484: add Readme version update
